#!/usr/bin/env bash
# Regenerate the hash-locked requirements files from the human-edited pins.
#
#   backend/requirements.txt           ->  requirements.lock.txt          (runtime)
#   backend/requirements-dev.txt       ->  requirements-dev.lock.txt      (runtime + test/lint tooling)
#   backend/requirements-tools.txt     ->  requirements-tools.lock.txt    (CI lint + security jobs)
#   backend/requirements-publish.txt   ->  requirements-publish.lock.txt  (twine, release path)
#
# requirements-tools.txt is generated too: it is the ruff/bandit/pip-audit subset of
# requirements-dev.txt, so those versions live in one place.
#
# Edit a version in the .txt file, run this script, commit every file it writes. CI (ci.yml, job
# requirements-lock) re-runs it and fails if the result differs, so a lock can never drift from its
# source pins. Every install in CI, the Dockerfile and action.yml uses `pip install --require-hashes`
# against a lock file: pip then refuses any artifact whose hash is not listed.
#
# Reproducibility: resolution is universal (markers for every platform), targets the lowest Python
# version the pinned set supports (numpy's pin requires >= 3.12), and ignores anything published
# after EXCLUDE_NEWER. Without that cut-off the resolution would change the moment any transitive
# dependency publishes a release, and the CI check would fail for no reason. Raise EXCLUDE_NEWER
# deliberately (it is how transitive dependencies get updated), then re-run this script.
#
#   Usage: backend/scripts/lock_requirements.sh   (needs uv: https://docs.astral.sh/uv/)

set -euo pipefail

cd "$(dirname "$0")/.."

PYTHON_VERSION="3.12"
EXCLUDE_NEWER="2026-10-03T00:00:00Z"
UV_ARGS=(
  --universal
  --generate-hashes
  --no-header
  --quiet
  --python-version "${PYTHON_VERSION}"
  --exclude-newer "${EXCLUDE_NEWER}"
)

header() {
  printf '# Hash-locked resolution of %s — DO NOT EDIT.\n' "$1"
  printf '# Regenerate with backend/scripts/lock_requirements.sh (uv, --universal, Python %s,\n' "${PYTHON_VERSION}"
  printf '# nothing published after %s).\n' "${EXCLUDE_NEWER}"
}

compile() {
  local source="$1" output="$2"
  local tmp
  tmp="$(mktemp)"
  uv pip compile "${UV_ARGS[@]}" "${source}" -o "${tmp}"
  { header "${source}"; cat "${tmp}"; } > "${output}"
  rm -f "${tmp}"
  echo "wrote ${output}"
}

# The tool subset is written to a file of its own first: uv records the path of its input in every
# "# via -r <path>" annotation, so compiling from a temporary file would put that path in the lock.
{
  echo "# The ruff, bandit and pip-audit pins of requirements-dev.txt — DO NOT EDIT."
  echo "# Generated by backend/scripts/lock_requirements.sh so the versions live in one place."
  grep -E '^(ruff|bandit|pip-audit)==' requirements-dev.txt
} > requirements-tools.txt
echo "wrote requirements-tools.txt"

compile "requirements.txt" "requirements.lock.txt"
compile "requirements-dev.txt" "requirements-dev.lock.txt"
compile "requirements-publish.txt" "requirements-publish.lock.txt"
compile "requirements-tools.txt" "requirements-tools.lock.txt"
